### ISSUE TITLE
Menu page nav bar mismatch

### ISSUE THREAD

**Issue by SathwikM27** [sathwikrao4545/IS601grp#8]
the Nav bar in menu page does not match the nav bar in home page

**Comment by sathwikrao4545** [comment]
Now the Nav Bar in Menu Matches with Nav bar in Home page.
Figma design of Menu page Updated.

<img width="362" alt="beforeNav" src="https://github.com/sathwikrao4545/IS601grp/assets/92375656/0aeadeb1-431b-41b9-9d42-8bde693da0e3">
<img width="551" alt="AfterNav" src="https://github.com/sathwikrao4545/IS601grp/assets/92375656/4db2856d-835e-411f-87d2-0c2d6534bfec">
